CREATE TABLE Venue (
    VenueID INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Location NVARCHAR(255) NOT NULL,
    Capacity INT NOT NULL,
    ImageUrl NVARCHAR(500)
);

CREATE TABLE Event (
    EventID INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    ImageUrl NVARCHAR(500),
    IsVenueAssigned BIT NOT NULL DEFAULT 0
);

CREATE TABLE Booking (
    BookingID INT PRIMARY KEY IDENTITY,
    VenueID INT NOT NULL,
    EventID INT NOT NULL,
    BookingDate DATETIME DEFAULT GETDATE(),
    Status NVARCHAR(50) NOT NULL,

    FOREIGN KEY (VenueID) REFERENCES Venue(VenueID) ON DELETE NO ACTION,
    FOREIGN KEY (EventID) REFERENCES Event(EventID) ON DELETE NO ACTION
);
